# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PitchPerfect' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'

  # Pods for PitchPerfect

  target 'PitchPerfect-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PitchPerfectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PitchPerfect-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PitchPerfect-tvOS

  target 'PitchPerfect-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
